# Change these first
owner: Fluff663 # Your GitHub organization or username, where this repository lives
repo: trackerstatus # The name of this repository

sites:
  - name: Abnormal
    url: $ABN
    icon: $ABNICON
    maxResponseTime: 1000
  - name: Aither
    url: $AIT
    icon: $AITICON
    maxResponseTime: 1000
  - name: AlphaRatio
    url: $AR
    icon: $AR_ICON
    maxResponseTime: 1000
  - name: AnimeBytes
    url: $AB
    icon: $AB_ICON
    maxResponseTime: 1000
  - name: AnimeTosho
    url: $AT
    icon: $AT_ICON
    maxResponseTime: 1000
  - name: Anthelion
    url: $ANT
    icon: $ANTICON
    maxResponseTime: 1000
  - name: AsianCinema
    url: $AC
    icon: $AC_ICON
    maxResponseTime: 1000
  - name: BakaBT
    url: $BBT
    icon: $BBT_ICON
    maxResponseTime: 1000
  - name: BitSexy
    url: $BS
    icon: $BS_ICON
    maxResponseTime: 1000
  - name: Blutopia
    url: $BLU
    icon: $BLU_ICON
    maxResponseTime: 1000
  - name: CGPeers
    url: $CGP
    icon: $CGP_ICON
    maxResponseTime: 1000
  - name: CathodeRay-Tube
    url: $CRT
    icon: $CRT_ICON
    maxResponseTime: 1000
  - name: DigitalCore
    url: $DC
    icon: $DC_ICON
    maxResponseTime: 1000
  - name: DocsPedia
    url: $DP
    icon: $DP_ICON
    maxResponseTime: 1000
  - name: FearNoPeer
    url: $FNP
    icon: $FNP_ICON
    maxResponseTime: 1000
  - name: FileList
    url: $FL
    icon: $FL_ICON
    maxResponseTime: 1000
  - name: GazelleGames
    url: $GGN
    icon: $GGN_ICON
    maxResponseTime: 1000
  - name: The Geeks
    url: $TGC
    icon: $TGC_ICON
    maxResponseTime: 1000
  - name: HDArea
    url: $HDA
    icon: $HDA_ICON
    maxResponseTime: 1000
  - name: IPTorrents
    url: $IPT
    icon: $IPT_ICON
    maxResponseTime: 1000
  - name: LST
    url: $LST
    icon: $LST_ICON
    maxResponseTime: 1000
  - name: Milkie
    url: $MLK
    icon: $MLK_ICON
    maxResponseTime: 1000
  - name: MyAnonaMouse
    url: $MAM
    icon: $MAM_ICON
    maxResponseTime: 1000
  - name: Nebulance
    url: $NEB
    icon: $NEB_ICON
    maxResponseTime: 1000
  - name: Old Toons World
    url: $OTW
    icon: $OTW_ICON
    maxResponseTime: 1000
  - name: Orpheus
    url: $OPS
    icon: $OPS_ICON
    maxResponseTime: 1000
  - name: Redacted
    url: $RED
    icon: $RED_ICON
    maxResponseTime: 1000
  - name: ReelFLiX
    url: $RFL
    icon: $RFL_ICON
    maxResponseTime: 1000

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: trstat.sylvy.me
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Tracker Status
  introTitle: "This is a status page for several private trackers."
  introMessage: "If you would like a tracker added/removed please send an email to fluff663@pm.me"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
